### ISSUE TITLE
CI/CD Process for Validating TITAN Modules

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/titan#2]

**Comment by asciifaceman** [comment]
OSS so we can probably start by getting her into circle or travis with a tf linter 

https://github.com/wata727/tflint

**Comment by naftulikay** [comment]
I'll likely end up building a simple variable/output parser to be able to validate that all input variables are exported and that the environment and hub modules expose all of the same variables/outputs that the underlying network module does.
