### ISSUE TITLE
Google Cloud Needs Service Activations

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/titan#49]
@blackstar257 has reported that because of the way that Google Cloud works, services need to be activated for a project before deployments can proceed.

We can, using the `data.google_client_config` provider and the `google_cloud_services` resource, activate the services required:

```hcl
data "google_client_config" "default" {}

resource "google_cloud_services" "default" {
  project = "${data.google_client_config.data.project}"
  services = ["X.googleapis.com"]
}
```

Hosted zones, compute, DNS, and others have been mentioned by @blackstar257.

**Comment by blackstar257** [comment]
* module.network.google_dns_managed_zone.public: 1 error(s) occurred:

* google_dns_managed_zone.public: Error creating DNS ManagedZone: googleapi: Error 403: Access Not Configured. Google Cloud DNS API has not been used in project 770909184332 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dns.googleapis.com/overview?project=770909184332 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured



* data.google_compute_zones.available: 1 error(s) occurred:

* data.google_compute_zones.available: data.google_compute_zones.available: googleapi: Error 403: Access Not Configured. Compute Engine API has not been used in project 770909184332 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=770909184332 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
* module.network.module.nat.data.google_compute_zones.available: 1 error(s) occurred:

* module.network.module.nat.data.google_compute_zones.available: data.google_compute_zones.available: googleapi: Error 403: Access Not Configured. Compute Engine API has not been used in project 770909184332 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=770909184332 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

**Comment by naftulikay** [comment]
Turning this into action items:

 - [ ] `dns.googleapis.com`
 - [ ] `compute.googleapis.com`

The issue here is that we need to somehow enforce that the creation of the `google_cloud_services` resource happens _before_ any access to anything; nothing in compute or DNS will work until these services have been activated.

There isn't a way to make a `module` use `depends_on` as far as I can tell. If there were, then at the project level, the `google_cloud_services` resource could be scheduled first.

**Comment by naftulikay** [comment]
I have a workaround: expose a `depends_on` list variable from the network module for manually ordering dependencies and hope that it works and isn't optimized out.

**Comment by naftulikay** [comment]
The problem here additionally is that `billing.googleapis.com` needs to be opened before anything else :man_facepalming:.

**Comment by naftulikay** [comment]
Closing this because it seems unsolvable with the way that Google APIs work. Additionally, Colossus will be migrated to [naftulikay/colossus](https://github.com/naftulikay/colossus) soon, as Titan != Colossus.

I'd love to provide some kind of bootstrap that would activate all of the requisite services, but whoever ran that Terraform would need super godlike billing powers and the average user won't have these.
