### ISSUE TITLE
[RFC] Create Tertiary Alias Ranges in GCP

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/titan#54]
In order to use GKE within Titan, each subnetwork must have at least _2_ alias ranges. We currently only provide one alias range for container hosting for each subnet.

Our current symmetry design uses the layer index to allocate the container alias range within the 200-249 range for the default layers. This means that for layer index zero, the VM subnet will be `10.x.0.0/23` and the container subnet will be `10.x.200.0/23`.

If the layer index is greater than or equal to 5, the secondary range will be wrapped to `150` and will continue upward until colliding with 200, meaning a maximum of 10 layers total. 99.9999% of Titan deployments won't need additional layers.

I'm not sure how to allocate these secondary ranges effectively. I can allocate `10.x.0.0/23` for VMs, `10.x.200.0/23` for containers, and perhaps `10.x.100.0/23` for the Kubernetes service alias range. The downside of doing this means that only five layers total will be supported:

 - `dmz-0`:
     - VM: `10.x.0.0/23`
     - Container: `10.x.200.0/23`
     - Kubernetes: `10.x.100.0/23`
 - `admin-4`:
     - VM: `10.x.48.0/23`
     - Container: `10.x.248.0/23`
     - Kubernetes: `10.x.148.0/23`

As can be seen, this will effectively occupy the following ranges:

 - `10.x.0.0` through `10.x.49.255` for VMs
 - `10.x.100.0` through `10.x.149.255` for Kubernetes
 - `10.x.200.0` through `10.x.249.255` for Containers

The only gaps in this allocation are from:

 - `10.x.50.0` through `10.x.99.255`
 - `10.x.150.0` through `10.x199.255`

This seems acceptable. If additional subnets are required, create them manually. This will, however, make the layer module not reusable.

For deploying multiple [`google_container_node_pool`](https://www.terraform.io/docs/providers/google/r/container_node_pool.html)s, it seems possible to have a cluster span multiple node pools which belong to different subnets. For managed instance groups, multiple regional MIGs can be created to shard nodes across subnets.

cc @blackstar257

**Comment by blackstar257** [comment]
Specifically when you say Kubernetes its specifically for kubernetes services.

https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by naftulikay** [comment]
Confirming that a Kubernetes cluster can have multiple node pools, meaning that the full space provided by a layer can be occupied by VMs and by containers.
