### ISSUE TITLE
Fix travis runs

### ISSUE THREAD

**Issue by smaslennikov** [naftulikay/titan#59]
https://github.com/naftulikay/titan/pull/58 showed AWS provider changes in terraform. The travis runs should be fixed to reflect these changes.

**Comment by smaslennikov** [comment]
Fixed in https://github.com/naftulikay/titan/pull/60 , but terraform wrapper `titan` is failing validations due to lack of creds.

**Comment by naftulikay** [comment]
I'm closing this because it does seem like we get green builds now.
